<#
.SYNOPSIS
    Generates docs/TWEAK-REFERENCE.md from the tweak definitions.
.DESCRIPTION
    The reference is generated rather than written by hand so it cannot drift
    out of sync with what the tool actually does. If a tweak's rationale changes,
    the documentation changes with it — there is no second copy to forget.

.EXAMPLE
    pwsh -File tools/Build-TweakReference.ps1
#>

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

$repoRoot = Split-Path -Parent $PSScriptRoot
$tweakDir = Join-Path $repoRoot 'data/tweaks'
$outputPath = Join-Path $repoRoot 'docs/TWEAK-REFERENCE.md'

$out = [System.Collections.ArrayList]::new()

$null = $out.Add('# Tweak Reference')
$null = $out.Add('')
$null = $out.Add('> Generated by `tools/Build-TweakReference.ps1` from `data/tweaks/*.json`. Do not edit by hand — edit the definitions and regenerate.')
$null = $out.Add('')
$null = $out.Add('Every tweak here is applied through the journal engine and can be reverted individually with:')
$null = $out.Add('')
$null = $out.Add('```powershell')
$null = $out.Add('.\FortressOne.ps1 -Revert -TweakId <id>')
$null = $out.Add('```')
$null = $out.Add('')

# --- Summary table ---------------------------------------------------------
$null = $out.Add('## Summary')
$null = $out.Add('')
$null = $out.Add('| Tweak | Tier | Risk | Impact | Reboot |')
$null = $out.Add('|---|---|---|---|---|')

$allTweaks = [System.Collections.ArrayList]::new()

foreach ($file in (Get-ChildItem -LiteralPath $tweakDir -Filter '*.json' | Sort-Object Name)) {
    $doc = Get-Content -LiteralPath $file.FullName -Raw | ConvertFrom-Json
    foreach ($tweak in $doc.tweaks) {
        $reboot = if (($tweak.PSObject.Properties.Name -contains 'requiresReboot') -and $tweak.requiresReboot) { 'yes' } else { 'no' }
        $null = $out.Add("| ``$($tweak.id)`` | $($tweak.tier) | $($tweak.risk) | $($tweak.impact) | $reboot |")
        $null = $allTweaks.Add([pscustomobject]@{ Pack = $doc.pack; File = $file.Name; Tweak = $tweak; Doc = $doc })
    }
}

$null = $out.Add('')

# --- Detail per pack -------------------------------------------------------
$packs = $allTweaks | Group-Object { $_.File } | Sort-Object Name

foreach ($group in $packs) {
    $doc = $group.Group[0].Doc
    $null = $out.Add('')
    $null = $out.Add("## $($doc.pack)")
    $null = $out.Add('')
    $null = $out.Add($doc.description)
    $null = $out.Add('')

    # Surface the editorial notes embedded in the definition files — these carry
    # the honest caveats and are the most valuable part of the data set.
    foreach ($prop in $doc.PSObject.Properties) {
        if ($prop.Name -like '_*') {
            $label = ($prop.Name -replace '^_', '' -replace '_', ' ')
            $null = $out.Add("> **$label**: $($prop.Value)")
            $null = $out.Add('')
        }
    }

    foreach ($entry in $group.Group) {
        $tweak = $entry.Tweak
        $null = $out.Add("### $($tweak.name)")
        $null = $out.Add('')
        $null = $out.Add("`` $($tweak.id) ``")
        $null = $out.Add('')

        $meta = @("**Tier:** $($tweak.tier)", "**Risk:** $($tweak.risk)", "**Impact:** $($tweak.impact)")
        if (($tweak.PSObject.Properties.Name -contains 'requiresReboot') -and $tweak.requiresReboot) {
            $meta += '**Requires restart**'
        }
        if (($tweak.PSObject.Properties.Name -contains 'os') -and $tweak.os) {
            $meta += "**Windows:** $($tweak.os -join ', ')"
        }
        $null = $out.Add(($meta -join ' &nbsp;·&nbsp; '))
        $null = $out.Add('')
        $null = $out.Add($tweak.rationale)
        $null = $out.Add('')
        $null = $out.Add('<details><summary>What it changes</summary>')
        $null = $out.Add('')
        $null = $out.Add('```')

        foreach ($action in $tweak.actions) {
            $value = if ($null -eq $action.value) { '<delete / absent>' } else { $action.value }
            switch ($action.provider) {
                'registry'      { $null = $out.Add("registry  $($action.path)\$($action.name) = $value") }
                'service'       { $null = $out.Add("service   $($action.name) -> $value") }
                'scheduledtask' { $null = $out.Add("task      $($action.taskPath)$($action.name) -> $value") }
                'power'         { $null = $out.Add("power     $($action.name) = $value") }
                'tcp'           { $null = $out.Add("tcp       $($action.name) = $value") }
                'netadapter'    { $null = $out.Add("nic       $($action.name) = $value") }
                'bcd'           { $null = $out.Add("bcdedit   $($action.name) = $value") }
                default         { $null = $out.Add("$($action.provider) $($action.name) = $value") }
            }
        }

        $null = $out.Add('```')
        $null = $out.Add('')
        $null = $out.Add('</details>')
        $null = $out.Add('')
    }
}

Set-Content -LiteralPath $outputPath -Value ($out -join "`n") -Encoding UTF8
Write-Host "Wrote $outputPath ($($allTweaks.Count) tweaks)" -ForegroundColor Green
